version: "3.8"
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "3000:11434"
    volumes:
      - ./ollama:/root/.ollama
    restart: always
#Move Toward a Public API only format
#  nginx:
#    container_name: nginx
#    image: nginx:stable-alpine
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro #/etc/nginx/nginx.conf
#      - ./nginx/ssl:/etc/nginx/ssl  # Mount the directory containing your SSL file
#    ports:
#      - 443:443
#    restart: always   
#    depends_on:
#      - hindalcobot
